# A simple action usage
name: Build Kernel
on:
  workflow_dispatch:

jobs:
  Build-Kernel:
    strategy:
      fail-fast: false
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
    - name: Build Kernel
      uses: dabao1955/kernel_build_action@main
      with:
          kernel-url: https://github.com/lualua99/Realking_kernel_sm8250
          kernel-dir: msm-4.19
          kernel-branch: main
          config: alioth_defconfig
          arch: arm64
          aosp-gcc: true
          aosp-clang: true
          ksu: false
          ksu-version: main
          android-version: 13
          aosp-clang-version: r450784d
          python-27: true
          disable-lto: true
          anykernel3: true
